name: pip CPU
on:
  workflow_dispatch:
  push:
jobs:
  pip-Test:
    runs-on: ubuntu-latest
    steps:
      - name: "Update system"
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt autoremove
      - name: "Install new g++"
        run: |
          sudo apt install g++
          g++ --version
      - name: "Download PLSSVM"
        run: |
          git clone https://github.com/SC-SGS/PLSSVM.git
          cd PLSSVM
          git checkout regression
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: "Create and activate virtual environment"
        run: |
          python -m venv venv
          source venv/bin/activate
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
      - name: "Install Python dependencies"
        run: |
          source $VIRTUAL_ENV/bin/activate
          pip install --upgrade pip
          pip install -r PLSSVM/install/python_requirements.txt
      - name: "Build PLSSVM locally via pip"
        run: |
          source $VIRTUAL_ENV/bin/activate
          cd PLSSVM
          pip install .
      - name: "Run examples"
        env:
          MPLBACKEND: Agg
        run: |
          source $VIRTUAL_ENV/bin/activate
          cd PLSSVM
          python examples/python/sklearn_like_svc.py
          python examples/python/sklearn_like_svr.py
          ls 
